import { query } from '../pool.js';

const settings = [
  // Brand
  { key: 'brand.name', uz: 'SODIQ SCHOOL', ru: 'SODIQ SCHOOL', en: 'SODIQ SCHOOL', group: 'brand' },
  { key: 'brand.tagline', uz: 'EST. 2018 · TASHKENT', ru: 'EST. 2018 · TASHKENT', en: 'EST. 2018 · TASHKENT', group: 'brand' },
  { key: 'brand.description',
    uz: "Toshkentdagi yetakchi xususiy maktab — yoshlarimizni dunyo TOP universitetlariga olib boruvchi xavfsiz ko'prik.",
    ru: 'Ведущая частная школа Ташкента — безопасный мост, ведущий нашу молодёжь в TOP университеты мира.',
    en: 'Tashkent\'s leading private school — a safe bridge taking our youth to the world\'s top universities.',
    group: 'brand',
  },

  // Contact
  { key: 'contact.phone', raw: '+998 78 888 80 80', group: 'contact' },
  { key: 'contact.phone_link', raw: '+998788888080', group: 'contact' },
  { key: 'contact.address',
    uz: "Toshkent, Yunusobod tumani, Amir Temur ko'chasi 142",
    ru: 'Ташкент, Юнусабадский район, ул. Амира Темура 142',
    en: 'Tashkent, Yunusobod district, Amir Temur street 142',
    group: 'contact',
  },
  { key: 'contact.hours',
    uz: 'Dushanba–Juma · 9:00–18:00',
    ru: 'Пн–Пт · 9:00–18:00',
    en: 'Mon–Fri · 9:00–18:00',
    group: 'contact',
  },
  { key: 'contact.telegram', raw: 'https://t.me/sodiq_school', group: 'contact' },
  { key: 'contact.instagram', raw: 'https://instagram.com/sodiqschool.uz', group: 'contact' },
  { key: 'contact.youtube', raw: 'https://youtube.com/@sodiq_school', group: 'contact' },

  // Hero (index)
  { key: 'hero.pill',
    uz: 'Qabul 2026–2027 ochiq · Joylar cheklangan',
    ru: 'Приём 2026–2027 открыт · Места ограничены',
    en: 'Admissions 2026–2027 open · Limited seats',
    group: 'hero',
  },
  { key: 'hero.title_main',
    uz: "Bizning o'quvchilar",
    ru: 'Наши ученики учатся в',
    en: 'Our students study at',
    group: 'hero',
  },
  { key: 'hero.title_accent',
    uz: 'Harvardda',
    ru: 'Гарварде',
    en: 'Harvard',
    group: 'hero',
  },
  { key: 'hero.title_suffix',
    uz: "o'qiydi",
    ru: '',
    en: '',
    group: 'hero',
  },
  { key: 'hero.lead',
    uz: "O'zbekistonda birinchi marta — Sodiq School o'quvchisi <strong>Harvardga kirdi</strong>. Bugun bizning o'quvchilar dunyoning <strong>TOP-100</strong> universitetlarida o'qishadi.",
    ru: 'Впервые в Узбекистане — ученик Sodiq School <strong>поступил в Гарвард</strong>. Сегодня наши ученики учатся в <strong>TOP-100</strong> университетах мира.',
    en: 'For the first time in Uzbekistan — a Sodiq School student <strong>got into Harvard</strong>. Today our students study at the world\'s <strong>TOP-100</strong> universities.',
    group: 'hero',
  },
  { key: 'hero.cta_primary',
    uz: 'Maslahat oling →',
    ru: 'Получить консультацию →',
    en: 'Get a consultation →',
    group: 'hero',
  },
  { key: 'hero.cta_secondary',
    uz: 'Natijalar bilan tanishing ↓',
    ru: 'Посмотреть результаты ↓',
    en: 'See our results ↓',
    group: 'hero',
  },

  // Hero stats
  { key: 'hero.stat_students_value', raw: '450', group: 'hero_stats' },
  { key: 'hero.stat_students_suffix', raw: '+', group: 'hero_stats' },
  { key: 'hero.stat_students_label', uz: "O'quvchi", ru: 'Учеников', en: 'Students', group: 'hero_stats' },
  { key: 'hero.stat_students_sub',
    uz: "Hozirda bizda ta'lim olishadi",
    ru: 'Сейчас учатся у нас',
    en: 'Currently studying with us',
    group: 'hero_stats',
  },
  { key: 'hero.stat_grants_value', raw: '20', group: 'hero_stats' },
  { key: 'hero.stat_grants_label', uz: 'Grantlar', ru: 'Гранты', en: 'Grants', group: 'hero_stats' },
  { key: 'hero.stat_grants_sub',
    uz: "O'quvchilarimiz olgan grantlar",
    ru: 'Гранты наших учеников',
    en: 'Grants our students received',
    group: 'hero_stats',
  },
  { key: 'hero.stat_abroad_value', raw: '100', group: 'hero_stats' },
  { key: 'hero.stat_abroad_label', uz: "Xorijda o'qiydi", ru: 'Учатся за рубежом', en: 'Study abroad', group: 'hero_stats' },
  { key: 'hero.stat_abroad_sub',
    uz: 'AQSH, Buyuk Britaniya, Koreya va Evropa',
    ru: 'США, Великобритания, Корея и Европа',
    en: 'USA, UK, Korea and Europe',
    group: 'hero_stats',
  },
  { key: 'hero.stat_ielts_value', raw: '7.5', group: 'hero_stats' },
  { key: 'hero.stat_ielts_label', raw: 'IELTS', group: 'hero_stats' },
  { key: 'hero.stat_ielts_sub',
    uz: "O'rtacha natijamiz",
    ru: 'Наш средний балл',
    en: 'Our average score',
    group: 'hero_stats',
  },
  { key: 'hero.stat_sat_value', raw: '1400', group: 'hero_stats' },
  { key: 'hero.stat_sat_label', raw: 'SAT', group: 'hero_stats' },
  { key: 'hero.stat_sat_sub',
    uz: "O'rtacha natijamiz",
    ru: 'Наш средний балл',
    en: 'Our average score',
    group: 'hero_stats',
  },

  // About home block
  { key: 'about_home.eyebrow', uz: 'Biz kimmiz?', ru: 'Кто мы?', en: 'Who we are', group: 'about_home' },
  { key: 'about_home.title',
    uz: 'Sodiq School — nima uchun eng yaxshi tanlov?',
    ru: 'Sodiq School — почему лучший выбор?',
    en: 'Sodiq School — why is it the best choice?',
    group: 'about_home',
  },
  { key: 'about_home.body',
    uz: "<p>Sodiq School — bu 7–11 sinfgacha bo'lgan o'quvchilarini dunyoning <strong>TOP universitetlariga</strong> kiritadigan xususiy maktab.</p><p>O'quvchilarga <strong>matematika, ingliz tili, tarix</strong> va bolaning shaxsiyati rivojlanishi uchun <strong>notiqlik san'ati</strong> va <strong>tanqidiy fikrlash</strong> darslari o'tiladi.</p><p>Dars beradigan ustozlar — <strong>8–25 yillik tajribaga ega</strong> mutaxassislar. Ular orasida ona tili, matematika va tarix darsliklarini yozgan <strong>muallif-o'qituvchilar</strong> bor.</p>",
    ru: '<p>Sodiq School — частная школа для учеников 7–11 классов, готовящая их к поступлению в <strong>топовые университеты мира</strong>.</p><p>Ученики изучают <strong>математику, английский, историю</strong>, а также <strong>ораторское искусство</strong> и <strong>критическое мышление</strong>.</p><p>Преподают опытные педагоги <strong>с опытом 8–25 лет</strong>, среди них — авторы школьных учебников.</p>',
    en: '<p>Sodiq School is a private school for grades 7–11 that prepares students for admission to the world\'s <strong>top universities</strong>.</p><p>Students learn <strong>math, English, history</strong>, plus <strong>public speaking</strong> and <strong>critical thinking</strong>.</p><p>Teachers have <strong>8–25 years of experience</strong> and include authors of national textbooks.</p>',
    group: 'about_home',
  },

  // Mission
  { key: 'mission.quote',
    uz: "Farzandingiz o'z tilini va qadriyatlarini yo'qotmasdan, dunyo bilan <span class=\"accent\">teng darajada raqobatlasha</span> oladigan bo'lib ulg'aysin.",
    ru: 'Пусть ваш ребёнок вырастет, не теряя родного языка и ценностей, и сможет <span class="accent">конкурировать на равных</span> с миром.',
    en: 'Let your child grow up keeping their language and values, and become able to <span class="accent">compete on equal terms</span> with the world.',
    group: 'mission',
  },
  { key: 'mission.subtitle',
    uz: "Biz bolani mustaqil fikrlashga va o'zi qaror qabul qilishga o'rgatamiz. Farzandingiz qayerda o'qisa ham, u hayotda o'z o'rnini topib ketadigan shaxs bo'lib chiqadi.",
    ru: 'Мы учим ребёнка мыслить самостоятельно и принимать решения. Где бы ваш ребёнок ни учился, он найдёт своё место в жизни.',
    en: 'We teach children to think independently and make their own decisions. Wherever your child studies, they will find their place in life.',
    group: 'mission',
  },
  { key: 'mission.label',
    uz: 'Bizning missiyamiz',
    ru: 'Наша миссия',
    en: 'Our mission',
    group: 'mission',
  },
  { key: 'mission.author',
    uz: 'Sodiq School jamoasi',
    ru: 'Команда Sodiq School',
    en: 'The Sodiq School team',
    group: 'mission',
  },

  // Pricing (new section on index)
  { key: 'pricing.eyebrow', uz: 'Narxlar', ru: 'Цены', en: 'Pricing', group: 'pricing' },
  { key: 'pricing.title',
    uz: "Oylik to'lov",
    ru: 'Ежемесячная оплата',
    en: 'Monthly tuition',
    group: 'pricing',
  },
  { key: 'pricing.label',
    uz: '7–11-sinflar uchun:',
    ru: 'Для 7–11 классов:',
    en: 'For grades 7–11:',
    group: 'pricing',
  },
  { key: 'pricing.amount', raw: '6 600 000', group: 'pricing' },
  { key: 'pricing.currency',
    uz: "so'm",
    ru: 'сум',
    en: 'soum',
    group: 'pricing',
  },
  { key: 'pricing.note',
    uz: '*Chegirmalar ham mavjud',
    ru: '*Доступны скидки',
    en: '*Discounts available',
    group: 'pricing',
  },
  { key: 'pricing.includes',
    uz: 'Barcha akademik fanlar|IELTS va SAT tayyorlov|Tarbiya fanlari|Universitetga hujjat topshirish yordami',
    ru: 'Все академические предметы|Подготовка к IELTS и SAT|Воспитательные предметы|Помощь в подаче документов в университеты',
    en: 'All academic subjects|IELTS and SAT preparation|Character subjects|University application assistance',
    group: 'pricing',
  },
  { key: 'pricing.cta',
    uz: 'Ariza topshirish →',
    ru: 'Подать заявку →',
    en: 'Apply →',
    group: 'pricing',
  },

  // Awards section (extra labels)
  { key: 'awards.subtitle',
    uz: "O'quvchilarimiz xalqaro musobaqalarda erishgan natijalari",
    ru: 'Результаты наших учеников на международных соревнованиях',
    en: "Our students' results at international competitions",
    group: 'awards',
  },
  { key: 'awards.summary_total_label',
    uz: 'Jami medallar',
    ru: 'Всего медалей',
    en: 'Total medals',
    group: 'awards',
  },
  { key: 'awards.summary_competitions_label',
    uz: 'Xalqaro musobaqa',
    ru: 'Международных конкурсов',
    en: 'International competitions',
    group: 'awards',
  },
  { key: 'awards.summary_winners_label',
    uz: "Sovrindor o'quvchi",
    ru: 'Учеников-призёров',
    en: 'Award-winning students',
    group: 'awards',
  },

  // Natijalar (results-dark) heading
  { key: 'results_dark.title',
    uz: "Natijalar o'zlari gapiradi",
    ru: 'Результаты говорят сами за себя',
    en: 'Results speak for themselves',
    group: 'results_dark',
  },
  { key: 'results_dark.subtitle',
    uz: 'IELTS, SAT natijalarimiz bilan tanishing',
    ru: 'Ознакомьтесь с нашими результатами IELTS и SAT',
    en: 'Take a look at our IELTS and SAT results',
    group: 'results_dark',
  },

  // Admissions section (index)
  { key: 'admissions.eyebrow', uz: 'Qabul 2026–2027', ru: 'Приём 2026–2027', en: 'Admissions 2026–2027', group: 'admissions' },
  { key: 'admissions.title',
    uz: 'Farzandingizni kelajak uchun hozirdan tayyorlang',
    ru: 'Готовьте ребёнка к будущему уже сегодня',
    en: "Prepare your child for the future today",
    group: 'admissions',
  },
  { key: 'admissions.desc',
    uz: "Qabul iyul oyida boshlanadi. Imtihondan yaxshi natija olgan o'quvchilarga ichki <strong>grant</strong> beriladi. Farzandingiz <strong>bepul</strong> yoki <strong>chegirma</strong> asosida o'qishi mumkin.",
    ru: 'Приём начинается в июле. Ученикам с высокими результатами вступительного экзамена предоставляется внутренний <strong>грант</strong>. Ваш ребёнок может учиться <strong>бесплатно</strong> или со <strong>скидкой</strong>.',
    en: 'Admissions start in July. Students with high entrance exam results receive an internal <strong>grant</strong>. Your child can study <strong>for free</strong> or with a <strong>discount</strong>.',
    group: 'admissions',
  },
  { key: 'admissions.scarcity',
    uz: "Joylar soni cheklangan — har sinfga atigi <strong>20 ta o'rin</strong>",
    ru: 'Места ограничены — всего <strong>20 мест</strong> на класс',
    en: 'Limited seats — only <strong>20 spots</strong> per grade',
    group: 'admissions',
  },

  // Footer copyright
  { key: 'footer.copyright',
    uz: '© 2025 Sodiq School. Barcha huquqlar himoyalangan.',
    ru: '© 2025 Sodiq School. Все права защищены.',
    en: '© 2025 Sodiq School. All rights reserved.',
    group: 'footer',
  },

  // Aboutpage hero
  { key: 'about_page.hero_eyebrow', uz: 'Biz haqimizda', ru: 'О нас', en: 'About us', group: 'about_page' },
  { key: 'about_page.hero_title',
    uz: "Sodiq School — maktab haqida, jamoa va natijalar",
    ru: 'Sodiq School — о школе, команда и результаты',
    en: 'Sodiq School — about the school, team and results',
    group: 'about_page',
  },
  { key: 'about_page.hero_lead',
    uz: "2022-yilda Toshkentda o'zbek o'quvchilarini dunyoning eng TOP universitetlariga tayyorlash uchun ochilgan xususiy maktab.",
    ru: 'Частная школа, открытая в 2022 году в Ташкенте для подготовки узбекских учеников к поступлению в топ-университеты мира.',
    en: 'A private school opened in 2022 in Tashkent to prepare Uzbek students for the world\'s top universities.',
    group: 'about_page',
  },

  // Mashgulotlar hero
  { key: 'mash.hero_eyebrow', uz: "Mashg'ulot va kurslar", ru: 'Занятия и курсы', en: 'Courses & lessons', group: 'mash' },
  { key: 'mash.hero_title',
    uz: 'Farzandingizning kelajagi <br>shu yerda boshlanadi',
    ru: 'Будущее вашего ребёнка <br>начинается здесь',
    en: "Your child's future <br>starts here",
    group: 'mash',
  },
  { key: 'mash.hero_lead',
    uz: 'Grant yutib, chet elda o\'qishga kirsa — siz <strong>$0 dan $400,000 gacha</strong> ta\'lim xarajatidan xalos bo\'lasiz.',
    ru: 'Если ребёнок выиграет грант и поступит за рубеж — вы освобождаетесь от расходов на обучение <strong>от $0 до $400,000</strong>.',
    en: 'If your child wins a grant and gets in abroad, you save <strong>from $0 to $400,000</strong> in tuition.',
    group: 'mash',
  },

  // Aloqa hero
  { key: 'aloqa.hero_eyebrow', uz: "Bog'lanish", ru: 'Связаться', en: 'Contact', group: 'aloqa' },
  { key: 'aloqa.hero_title',
    uz: "Biz bilan bog'laning",
    ru: 'Свяжитесь с нами',
    en: 'Get in touch',
    group: 'aloqa',
  },
  { key: 'aloqa.hero_lead',
    uz: 'Savollaringiz bormi yoki ariza topshirmoqchimisiz? Quyidagi formani to\'ldiring — biz 24 soat ichida javob beramiz.',
    ru: 'Есть вопросы или хотите подать заявку? Заполните форму — мы ответим в течение 24 часов.',
    en: 'Have questions or want to apply? Fill out the form — we will respond within 24 hours.',
    group: 'aloqa',
  },

  // Blog hero
  { key: 'blog.hero_eyebrow', uz: 'Blog', ru: 'Блог', en: 'Blog', group: 'blog' },
  { key: 'blog.hero_title',
    uz: 'Foydali maqolalar',
    ru: 'Полезные статьи',
    en: 'Useful articles',
    group: 'blog',
  },
  { key: 'blog.hero_lead',
    uz: "IELTS, SAT, AQSh va Yevropa universitetlari uchun ariza, motivatsion xat va o'qish bo'yicha amaliy qo'llanmalar.",
    ru: 'IELTS, SAT, заявки в университеты США и Европы, мотивационные письма и практические руководства.',
    en: 'IELTS, SAT, applications to US/European universities, motivation letters and practical study guides.',
    group: 'blog',
  },

  // Natijalar hero
  { key: 'natijalar.hero_eyebrow', uz: 'Bizning natijalar', ru: 'Наши результаты', en: 'Our results', group: 'natijalar' },
  { key: 'natijalar.hero_title',
    uz: "O'quvchilar natijalari",
    ru: 'Результаты учеников',
    en: 'Student results',
    group: 'natijalar',
  },
  { key: 'natijalar.hero_lead',
    uz: 'Talabalarimizning IELTS va SAT imtihonlarida erishgan natijalari va dunyoga ochilgan eshiklar.',
    ru: 'Результаты наших студентов на IELTS и SAT, и двери, открытые в мир.',
    en: 'Our students\' IELTS and SAT results, and doors opened to the world.',
    group: 'natijalar',
  },
];

export async function seedSettings() {
  console.log('[seed] settings...');
  for (const s of settings) {
    await query(
      `INSERT INTO settings (\`key\`, value_uz, value_ru, value_en, value_raw, \`group\`)
       VALUES (?, ?, ?, ?, ?, ?)`,
      [s.key, s.uz ?? null, s.ru ?? null, s.en ?? null, s.raw ?? null, s.group ?? 'general'],
    );
  }
}
